version: '2'

services:
    db:
        image: mysql:5.6
        command: mysqld --sql_mode=""
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 46jpw4
