version: '2'

networks:
  vpcboot:
    driver: bridge
    ipam:
     config:
       - subnet: 14.5.0.0/16
         gateway: 14.5.0.1

services:
    db:
        image: mysql:5.6
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 46jpw4
        networks:
            vpcboot:
                ipv4_address: 14.5.0.5
    local:
        image: bootlocal
        ports:
            - "80:8080"
        volumes:
            - ./tomcat/code/target/AssessmentSystem.war:/usr/local/tomcat/webapps/ROOT.war
            - ./tomcat/code/target/AssessmentSystem:/usr/local/tomcat/webapps/ROOT
            - ./tomcat/code/ambiente:/usr/local/tomcat/ambiente
            - ./tomcat/code/students:/usr/local/tomcat/students
            - ./tomcat/config/ini:/usr/local/tomcat/ini
        networks:
            vpcboot:
                ipv4_address: 14.5.0.6

