version: '2'

services:
    db:
        image: mysql:5.6
        command: mysqld --sql_mode=""
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 46jpw4
    halyentomcat:
        image: halyentomcat
        links:
            - db
        ports:
            - "8000:8080"
        volumes:
            - ./tomcat/code/target/AssessmentSystem.war:/usr/local/tomcat/webapps/ROOT.war
            - ./tomcat/code/target/AssessmentSystem:/usr/local/tomcat/webapps/ROOT    
